### ISSUE TITLE
you have to provide insrtuctions to use it and dependencires

### ISSUE THREAD

**Issue by normalentity** [JignasP/CalculusOCR#3]
/_parse_latex_antlr.py", line 66, in parse_latex
    raise ImportError("LaTeX parsing requires the antlr4 Python package,"
ImportError: LaTeX parsing requires the antlr4 Python package, provided by pip (antlr4-python3-runtime) or conda (antlr-python-runtime), version 4.11

**Additional context**

**Comment by JignasP** [comment]
Commited a change to install antlr4-python3-runtime version 4.11 during install.

**Comment by JignasP** [comment]
And note that if this error occurs, it can be frxed by:

pip install antlr4-python3-runtime==4.11.0
